export const variants = [
  {
    id: 1,
    slug: "v-mute-core-black",
    color: "BLACK",
    price: 89.0,
    stock: 150,
    photos: "",
  },
  {
    id: 1,
    slug: "v-mute-core-red",
    color: "RED",
    price: 89.0,
    stock: 80,
    photos: "",
  },
  {
    id: 1,
    slug: "v-mute-core-white",
    color: "WHITE",
    price: 89.0,
    stock: 100,
    photos: "",
  },
  {
    id: 2,
    slug: "v-mute-advance-black",
    color: "BLACK",
    price: 159.0,
    stock: 120,
    photos: "",
  },
  {
    id: 2,
    slug: "v-mute-advance-red",
    color: "RED",
    price: 159.0,
    stock: 45,
    photos: "",
  },
  {
    id: 2,
    slug: "v-mute-advance-white",
    color: "WHITE",
    price: 159.0,
    stock: 60,
    photos: "",
  },

  {
    id: 3,
    slug: "v-mute-pro-black",
    color: "BLACK",
    price: 299.0,
    stock: 50,
    photos: "",
  },
  {
    id: 3,
    slug: "v-mute-pro-red",
    color: "RED",
    price: 299.0,
    stock: 20,
    photos: "",
  },
  {
    id: 3,
    slug: "v-mute-pro-white",
    color: "WHITE",
    price: 299.0,
    stock: 30,
    photos: "",
  },

  {
    id: 4,
    slug: "v-flow-go-black",
    color: "BLACK",
    price: 69.0,
    stock: 200,
    photos: "",
  },
  {
    id: 4,
    slug: "v-flow-go-red",
    color: "RED",
    price: 69.0,
    stock: 100,
    photos: "",
  },
  {
    id: 4,
    slug: "v-flow-go-white",
    color: "WHITE",
    price: 69.0,
    stock: 150,
    photos: "",
  },

  {
    id: 5,
    slug: "v-flow-anc-black",
    color: "BLACK",
    price: 149.0,
    stock: 90,
    photos: "",
  },
  {
    id: 5,
    slug: "v-flow-anc-red",
    color: "RED",
    price: 149.0,
    stock: 40,
    photos: "",
  },
  {
    id: 5,
    slug: "v-flow-anc-white",
    color: "WHITE",
    price: 149.0,
    stock: 60,
    photos: "",
  },

  {
    id: 6,
    slug: "v-roam-mini-black",
    color: "BLACK",
    price: 59.0,
    stock: 300,
    photos: "",
  },
  {
    id: 6,
    slug: "v-roam-mini-red",
    color: "RED",
    price: 59.0,
    stock: 150,
    photos: "",
  },
  {
    id: 6,
    slug: "v-roam-mini-white",
    color: "WHITE",
    price: 59.0,
    stock: 100,
    photos: "",
  },

  {
    id: 7,
    slug: "v-roam-beast-black",
    color: "BLACK",
    price: 329.0,
    stock: 40,
    photos: "",
  },
  {
    id: 7,
    slug: "v-roam-beast-red",
    color: "RED",
    price: 329.0,
    stock: 15,
    photos: "",
  },
  {
    id: 7,
    slug: "v-roam-beast-white",
    color: "WHITE",
    price: 329.0,
    stock: 20,
    photos: "",
  },

  {
    id: 8,
    slug: "v-stage-solo-black",
    color: "BLACK",
    price: 199.0,
    stock: 60,
    photos: "",
  },
  {
    id: 8,
    slug: "v-stage-solo-red",
    color: "RED",
    price: 199.0,
    stock: 10,
    photos: "",
  },
  {
    id: 8,
    slug: "v-stage-solo-white",
    color: "WHITE",
    price: 199.0,
    stock: 30,
    photos: "",
  },

  {
    id: 9,
    slug: "v-stage-cinema-black",
    color: "BLACK",
    price: 549.0,
    stock: 25,
    photos: "",
  },
  {
    id: 9,
    slug: "v-stage-cinema-red",
    color: "RED",
    price: 549.0,
    stock: 5,
    photos: "",
  },
  {
    id: 9,
    slug: "v-stage-cinema-white",
    color: "WHITE",
    price: 549.0,
    stock: 10,
    photos: "",
  },

  {
    id: 10,
    slug: "v-sense-mini-black",
    color: "BLACK",
    price: 89.0,
    stock: 110,
    photos: "",
  },
  {
    id: 10,
    slug: "v-sense-mini-white",
    color: "WHITE",
    price: 89.0,
    stock: 140,
    photos: "",
  },
];
